name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      # We build our library first because JSII generates
      # the tsconfig.json file, which is needed by eslint
      - name: Build lib
        run: npm run build

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm test
